name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -yq --no-install-recommends gfortran make python3-sphinx python3-sphinx-rtd-theme
    - run: make FC=gfortran -C doc/src
    - run: make -C scf
    - run: make html
